application: notebunnies
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: .*/(bunny-.*\.css)
  mime_type: text/css
  static_files: templates/elements/\1
  upload: templates/elements/(.*\.css)
- url: .*/(.*\.css)
  mime_type: text/css
  static_files: css/\1
  upload: css/(.*\.css)
- url: .*/(bunny-.*\.js)
  mime_type: text/javascript
  static_files: templates/elements/\1
  upload: templates/elements/(.*\.js)
- url: .*/(.*\.js)
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.*\.js)
- url: .*/(.*\.svg)
  mime_type: image/svg+xml
  static_files: svg/\1
  upload: svg/(.*\.svg)
- url: .*/(bunny-.*\.html)
  mime_type: text/html
  static_files: templates/elements/\1
  upload: templates/elements/(.*\.html)
- url: .*/(bunny-.*\.txt)
  mime_type: text/html
  static_files: templates/elements/\1
  upload: templates/elements/(.*\.txt)
- url: .*/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: img/\1
  upload: img/(.*\.(bmp|gif|ico|jpeg|jpg|png))
# This should always go last:
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
